baseURL: "https://abirarsalane.github.io/"
languageCode: en-us
title: Abir Arsalane
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: achievements
      name: Achievements
      url: /achievements
      weight: 50
    - identifier: search
      name: Search
      url: /search
      weight: 60
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 70
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 80

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Abir Arsalane"
    subtitle: An alumna of Mathematics and Informatics Olympiads, trained by experts from Google, Amazon and Hugging Face, I am a final-year Big Data & AI Engineering student currently interning as a data scientist at the Innovation Stream of Orange Business. My focus is on solving complex problems creatively and innovatively through AI. My current hobby is experimenting with LLMs, diving deep into GenAI, and exploring what it takes to reach its full potential. I am keen to collaborate and create impactful solutions in the world of data and AI. Discover some of my latest work, and let's connect to shape the future!
    imageUrl: "home/photo.jpg"
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:abir.arsalane@outlook.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/abir-arsalane/"
    - name: "github"
      url: "https://github.com/abirarsalane"
    #- name: "youtube"
    #  url: "https://www.youtube.com/c/AbdurRahmanKalim"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
